metadata:
  labels:
    app: ${project.artifactId}
    project: ${project.artifactId}
    hystrix.enabled: true
    hystrix.cluster: default
    version: ${project.version}
  annotations:
    configmap.fabric8.io/update-on-change: alfresco-blockchain-agent-properties
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ${docker.registry.push.secret-name}
      containers:
        - env:
          - name: ALFRESCO_USERNAME
            valueFrom:
             secretKeyRef:
                name: alfresco-blockchain-agent-secrets
                key: ALFRESCO_USERNAME
          - name: ALFRESCO_PASSWORD
            valueFrom:
             secretKeyRef:
                name: alfresco-blockchain-agent-secrets
                key: ALFRESCO_PASSWORD
          - name: BLOCKCHAIN_CERT_PATH
            valueFrom:
             configMapKeyRef:
                name: alfresco-blockchain-agent-env
                key: BLOCKCHAIN_CERT_PATH
          - name: BLOCKCHAIN_CERT_PASSWORD
            valueFrom:
             secretKeyRef:
                name: alfresco-blockchain-agent-secrets
                key: BLOCKCHAIN_CERT_PASSWORD
          - name: BLOCKCHAIN_CERT_ALIAS
            valueFrom:
             configMapKeyRef:
                name: alfresco-blockchain-agent-env
                key: BLOCKCHAIN_CERT_ALIAS
          - name: BLOCKCHAIN_CONSUMER_KEY
            valueFrom:
             secretKeyRef:
                name: alfresco-blockchain-agent-secrets
                key: BLOCKCHAIN_CONSUMER_KEY
          - name: BLOCKCHAIN_CONSUMER_SECRET
            valueFrom:
             secretKeyRef:
                name: alfresco-blockchain-agent-secrets
                key: BLOCKCHAIN_CONSUMER_SECRET
          volumeMounts:
          - name: alfresco-blockchain-agent-secrets
            mountPath: /tmp/cert/Alfresco-Blockchain.pfx
            subPath: alfresco-blockchain-cert
          - name: alfresco-blockchain-agent-properties
            mountPath: /deployments/config/application.properties
            subPath: application.properties
      volumes:
      - name: alfresco-blockchain-agent-secrets
        secret:
          secretName: alfresco-blockchain-agent-secrets
      - name: alfresco-blockchain-agent-properties
        configMap:
          name: alfresco-blockchain-agent-properties
          defaultMode: 420
          items:
          - key: application.properties
            path: application.properties
